// Pattern check: no GoF pattern (-) — rejected — pure repo-skeleton file
// generators wrapping the existing compiler Strategy; string templating, no
// abstraction.
//
// Builds a ready-to-push firmware PROJECT bundle (not just the keymap files):
// the full repo skeleton + CI workflow + README the user can drop on GitHub
// (Actions builds the binary) or build locally. This is the Phase-1 zero-dep
// fallback — it never needs the cloud. The keymap/overlay/keymap.c come straight
// from the compilers (getCompiler); this module adds the surrounding scaffolding.

import type { ExportedFile } from '../types'
import type { Diagnostic } from './diagnostics'
import { getCompiler } from './compiler'
import { resolveController } from './controller'
import { buildQmkKeyboardJson } from './compilers/qmkKeyboardJson'
import type { CanonAction, ConfigKeymap, Target } from './types'

export interface ProjectBundle {
    /** Files whose `filename` is the path INSIDE the archive. */
    files: ExportedFile[]
    diagnostics: Diagnostic[]
    /** Suggested archive base name (no extension). */
    rootName: string
}

const sanitize = (s: string): string =>
    s
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '') || 'remappr'

const asText = (c: string | Uint8Array): string =>
    typeof c === 'string' ? c : new TextDecoder().decode(c)

const text = (filename: string, content: string): ExportedFile => ({
    filename,
    mime: 'text/plain',
    content,
})

/** Walk every action in the config (layers, encoders, combos, …) for feature flags. */
function someAction(
    config: ConfigKeymap,
    pred: (a: CanonAction) => boolean,
): boolean {
    for (const layer of config.layers) {
        if (layer.bindings.some(pred)) return true
        for (const e of layer.encoders ?? []) {
            if (pred(e.cw) || pred(e.ccw) || (e.press && pred(e.press)))
                return true
        }
    }
    return (config.combos ?? []).some((c) => pred(c.action))
}

/* ── ZMK ─────────────────────────────────────────────────────────────────── */

function zmkConf(config: ConfigKeymap): string {
    const uses = (pred: (a: CanonAction) => boolean): boolean =>
        someAction(config, pred)
    const flag = (on: boolean, line: string): string =>
        on ? line : `# ${line}`
    return [
        `# ZMK config for ${config.meta.name}`,
        `# Generated by remappr — adjust to your board.`,
        ``,
        `CONFIG_ZMK_STUDIO=y`,
        flag(
            uses((a) => a.type === 'lighting' && a.target === 'underglow'),
            `CONFIG_ZMK_RGB_UNDERGLOW=y`,
        ),
        flag(
            uses((a) => a.type === 'lighting' && a.target === 'backlight'),
            `CONFIG_ZMK_BACKLIGHT=y`,
        ),
        flag(
            uses(
                (a) =>
                    a.type === 'mouse_key' ||
                    a.type === 'mouse_move' ||
                    a.type === 'mouse_scroll',
            ),
            `CONFIG_ZMK_POINTING=y`,
        ),
        ``,
    ].join('\n')
}

const ZMK_BUILD_WORKFLOW = [
    `name: Build ZMK firmware`,
    `on: [push, pull_request, workflow_dispatch]`,
    `jobs:`,
    `  build:`,
    `    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main`,
    ``,
].join('\n')

const ZMK_WEST_YML = [
    `manifest:`,
    `  remotes:`,
    `    - name: zmkfirmware`,
    `      url-base: https://github.com/zmkfirmware`,
    `  projects:`,
    `    - name: zmk`,
    `      remote: zmkfirmware`,
    `      revision: main`,
    `      import: app/west.yml`,
    `  self:`,
    `    path: config`,
    ``,
].join('\n')

function zmkBundle(config: ConfigKeymap): ProjectBundle {
    const ctrl = resolveController(config)
    const shield = sanitize(
        ctrl.shield || config.keyboard.id || config.meta.name,
    )
    const board = ctrl.board || 'YOUR_BOARD'
    const { files: compiled, diagnostics } = getCompiler('zmk').compile(config)
    const keymap = compiled.find((f) => f.filename.endsWith('.keymap'))
    const overlay = compiled.find((f) => f.filename.endsWith('.overlay'))

    const buildYaml = [
        `include:`,
        `  - board: ${board}`,
        `    shield: ${shield}`,
        ``,
    ].join('\n')

    const readme = [
        `# ${config.meta.name} — ZMK config`,
        ``,
        `Generated by remappr. This is a ready-to-build \`zmk-config\` repo.`,
        ``,
        `## Build in the cloud (no toolchain)`,
        `1. Create a new GitHub repository and push these files.`,
        `2. The included workflow (\`.github/workflows/build.yml\`) builds on every push.`,
        `3. Open the Actions run → download the \`firmware\` artifact (\`.uf2\`).`,
        ``,
        `## Build locally`,
        `\`\`\`sh`,
        `west init -l config && west update`,
        `west build -b ${board} -- -DSHIELD=${shield}`,
        `\`\`\``,
        ``,
        `## Notes`,
        `- Set \`board\` in \`build.yaml\` to your actual controller (currently \`${board}\`).`,
        `- \`config/${shield}.overlay\` holds the physical-layout / matrix-transform`,
        `  (and kscan, if you defined board hardware in remappr). For a fully custom`,
        `  shield, move hardware nodes into \`boards/shields/${shield}/\`.`,
        ``,
    ].join('\n')

    const files: ExportedFile[] = [
        text(`config/${shield}.keymap`, keymap ? asText(keymap.content) : ''),
        text(`config/${shield}.conf`, zmkConf(config)),
    ]
    if (overlay)
        files.push(text(`config/${shield}.overlay`, asText(overlay.content)))
    files.push(
        text(`config/west.yml`, ZMK_WEST_YML),
        text(`build.yaml`, buildYaml),
        text(`.github/workflows/build.yml`, ZMK_BUILD_WORKFLOW),
        text(`README.md`, readme),
    )

    return { files, diagnostics, rootName: `${shield}-zmk-config` }
}

/* ── QMK ─────────────────────────────────────────────────────────────────── */

const QMK_BUILD_WORKFLOW = [
    `name: Build QMK firmware`,
    `on: [push, pull_request, workflow_dispatch]`,
    `jobs:`,
    `  build:`,
    `    uses: qmk/.github/workflows/qmk_userspace_build.yml@main`,
    `    with:`,
    `      qmk_repo: qmk/qmk_firmware`,
    `      qmk_ref: master`,
    ``,
].join('\n')

// Minimal QMK `config.h`. The matrix wiring (matrix_pins + diode_direction), the
// MCU/USB identity and the feature toggles now live in `keyboard.json` (the modern
// QMK data-driven form); config.h is kept only for board-level overrides QMK can't
// express in JSON (e.g. a WS2812 SPI driver), so the skeleton stays a valid keymap.
function qmkConfigH(): string {
    return (
        [
            `#pragma once`,
            `// remappr — board-level overrides go here.`,
            `// Matrix pins, diode direction, processor/bootloader and USB identity`,
            `// are data-driven in keyboard.json; add only extras config.h must`,
            `// carry (e.g. #define WS2812_SPI_DRIVER SPID2).`,
        ].join('\n') + '\n'
    )
}

function qmkBundle(config: ConfigKeymap, target: Target): ProjectBundle {
    const kb = sanitize(config.keyboard.id || config.meta.name)
    const km = 'remappr'
    const { files: compiled, diagnostics } = getCompiler(target).compile(config)
    const keymapC = compiled.find((f) => f.filename.endsWith('.c'))
    const kbDir = `keyboards/${kb}`
    const base = `${kbDir}/keymaps/${km}`
    const { json: keyboardJson, diagnostics: kbDiag } =
        buildQmkKeyboardJson(config)

    const qmkJson = JSON.stringify(
        { userspace_version: '1.1', build_targets: [[kb, km]] },
        null,
        2,
    )

    const readme = [
        `# ${config.meta.name} — QMK keyboard + userspace`,
        ``,
        `Generated by remappr as a \`qmk_userspace\` tree with a complete`,
        `keyboard definition (\`${kbDir}/keyboard.json\`).`,
        ``,
        `## Build in the cloud`,
        `1. Push these files to a GitHub repo (a fork of \`qmk/qmk_userspace\` works).`,
        `2. The included workflow builds the keymap on every push.`,
        `3. Download the firmware artifact from the Actions run.`,
        ``,
        `## Build locally`,
        `\`\`\`sh`,
        `qmk userspace-compile`,
        `# or: qmk compile -kb ${kb} -km ${km}`,
        `\`\`\``,
        ``,
        `## Notes`,
        `- \`${kbDir}/keyboard.json\` is the data-driven keyboard definition`,
        `  (matrix pins, diode direction, MCU/USB identity, features, layout).`,
        `- Verify the pin names + processor/bootloader against your hardware before`,
        `  flashing — remappr fills them from the builder's Controller panel.`,
        ``,
    ].join('\n')

    const files: ExportedFile[] = [
        text(
            `${kbDir}/keyboard.json`,
            JSON.stringify(keyboardJson, null, 4) + '\n',
        ),
        text(`${base}/keymap.c`, keymapC ? asText(keymapC.content) : ''),
        text(
            `${base}/rules.mk`,
            `# remappr keymap — feature toggles live in keyboard.json\n`,
        ),
        text(`${base}/config.h`, qmkConfigH()),
        text(`qmk.json`, qmkJson + '\n'),
        text(`.github/workflows/build_binaries.yml`, QMK_BUILD_WORKFLOW),
        text(`README.md`, readme),
    ]

    return {
        files,
        diagnostics: [...diagnostics, ...kbDiag],
        rootName: `${kb}-qmk-userspace`,
    }
}

/** Build the full project bundle for a target. ZMK → zmk-config skeleton;
 *  QMK/Keychron → qmk_userspace skeleton. */
export function buildProjectBundle(
    config: ConfigKeymap,
    target: Target,
): ProjectBundle {
    return target === 'zmk' ? zmkBundle(config) : qmkBundle(config, target)
}
