// Pattern check: no GoF pattern (-) — rejected — pure repo-skeleton file
// generators wrapping the existing compiler Strategy; string templating, no
// abstraction.
//
// Builds a ready-to-push firmware PROJECT bundle (not just the keymap files):
// the full repo skeleton + CI workflow + README the user can drop on GitHub
// (Actions builds the binary) or build locally. This is the Phase-1 zero-dep
// fallback — it never needs the cloud. The keymap/overlay/keymap.c come straight
// from the compilers (getCompiler); this module adds the surrounding scaffolding.

import type { ExportedFile } from '../types'
import type { Diagnostic } from './diagnostics'
import { getCompiler } from './compiler'
import { resolveQmkPin } from './pinmaps'
import { resolveController } from './controller'
import type { CanonAction, ConfigKeymap, Target } from './types'

export interface ProjectBundle {
    /** Files whose `filename` is the path INSIDE the archive. */
    files: ExportedFile[]
    diagnostics: Diagnostic[]
    /** Suggested archive base name (no extension). */
    rootName: string
}

const sanitize = (s: string): string =>
    s
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '') || 'remappr'

const asText = (c: string | Uint8Array): string =>
    typeof c === 'string' ? c : new TextDecoder().decode(c)

const text = (filename: string, content: string): ExportedFile => ({
    filename,
    mime: 'text/plain',
    content,
})

/** Walk every action in the config (layers, encoders, combos, …) for feature flags. */
function someAction(
    config: ConfigKeymap,
    pred: (a: CanonAction) => boolean,
): boolean {
    for (const layer of config.layers) {
        if (layer.bindings.some(pred)) return true
        for (const e of layer.encoders ?? []) {
            if (pred(e.cw) || pred(e.ccw) || (e.press && pred(e.press)))
                return true
        }
    }
    return (config.combos ?? []).some((c) => pred(c.action))
}

/* ── ZMK ─────────────────────────────────────────────────────────────────── */

function zmkConf(config: ConfigKeymap): string {
    const uses = (pred: (a: CanonAction) => boolean): boolean =>
        someAction(config, pred)
    const flag = (on: boolean, line: string): string =>
        on ? line : `# ${line}`
    return [
        `# ZMK config for ${config.meta.name}`,
        `# Generated by remappr — adjust to your board.`,
        ``,
        `CONFIG_ZMK_STUDIO=y`,
        flag(
            uses((a) => a.type === 'lighting' && a.target === 'underglow'),
            `CONFIG_ZMK_RGB_UNDERGLOW=y`,
        ),
        flag(
            uses((a) => a.type === 'lighting' && a.target === 'backlight'),
            `CONFIG_ZMK_BACKLIGHT=y`,
        ),
        flag(
            uses(
                (a) =>
                    a.type === 'mouse_key' ||
                    a.type === 'mouse_move' ||
                    a.type === 'mouse_scroll',
            ),
            `CONFIG_ZMK_POINTING=y`,
        ),
        ``,
    ].join('\n')
}

const ZMK_BUILD_WORKFLOW = [
    `name: Build ZMK firmware`,
    `on: [push, pull_request, workflow_dispatch]`,
    `jobs:`,
    `  build:`,
    `    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main`,
    ``,
].join('\n')

const ZMK_WEST_YML = [
    `manifest:`,
    `  remotes:`,
    `    - name: zmkfirmware`,
    `      url-base: https://github.com/zmkfirmware`,
    `  projects:`,
    `    - name: zmk`,
    `      remote: zmkfirmware`,
    `      revision: main`,
    `      import: app/west.yml`,
    `  self:`,
    `    path: config`,
    ``,
].join('\n')

function zmkBundle(config: ConfigKeymap): ProjectBundle {
    const ctrl = resolveController(config)
    const shield = sanitize(
        ctrl.shield || config.keyboard.id || config.meta.name,
    )
    const board = ctrl.board || 'YOUR_BOARD'
    const { files: compiled, diagnostics } = getCompiler('zmk').compile(config)
    const keymap = compiled.find((f) => f.filename.endsWith('.keymap'))
    const overlay = compiled.find((f) => f.filename.endsWith('.overlay'))

    const buildYaml = [
        `include:`,
        `  - board: ${board}`,
        `    shield: ${shield}`,
        ``,
    ].join('\n')

    const readme = [
        `# ${config.meta.name} — ZMK config`,
        ``,
        `Generated by remappr. This is a ready-to-build \`zmk-config\` repo.`,
        ``,
        `## Build in the cloud (no toolchain)`,
        `1. Create a new GitHub repository and push these files.`,
        `2. The included workflow (\`.github/workflows/build.yml\`) builds on every push.`,
        `3. Open the Actions run → download the \`firmware\` artifact (\`.uf2\`).`,
        ``,
        `## Build locally`,
        `\`\`\`sh`,
        `west init -l config && west update`,
        `west build -b ${board} -- -DSHIELD=${shield}`,
        `\`\`\``,
        ``,
        `## Notes`,
        `- Set \`board\` in \`build.yaml\` to your actual controller (currently \`${board}\`).`,
        `- \`config/${shield}.overlay\` holds the physical-layout / matrix-transform`,
        `  (and kscan, if you defined board hardware in remappr). For a fully custom`,
        `  shield, move hardware nodes into \`boards/shields/${shield}/\`.`,
        ``,
    ].join('\n')

    const files: ExportedFile[] = [
        text(`config/${shield}.keymap`, keymap ? asText(keymap.content) : ''),
        text(`config/${shield}.conf`, zmkConf(config)),
    ]
    if (overlay)
        files.push(text(`config/${shield}.overlay`, asText(overlay.content)))
    files.push(
        text(`config/west.yml`, ZMK_WEST_YML),
        text(`build.yaml`, buildYaml),
        text(`.github/workflows/build.yml`, ZMK_BUILD_WORKFLOW),
        text(`README.md`, readme),
    )

    return { files, diagnostics, rootName: `${shield}-zmk-config` }
}

/* ── QMK ─────────────────────────────────────────────────────────────────── */

const QMK_BUILD_WORKFLOW = [
    `name: Build QMK firmware`,
    `on: [push, pull_request, workflow_dispatch]`,
    `jobs:`,
    `  build:`,
    `    uses: qmk/.github/workflows/qmk_userspace_build.yml@main`,
    `    with:`,
    `      qmk_repo: qmk/qmk_firmware`,
    `      qmk_ref: master`,
    ``,
].join('\n')

// Build the QMK `config.h` body, emitting pin #defines from the builder's
// friendly pin labels: `keyboard.pins` → MATRIX_ROW_PINS/MATRIX_COL_PINS, else
// per-key `pin` → DIRECT_PINS (one row; QMK wants a rows×cols grid, so warn).
// QMK pin tokens are usually the silkscreen label already (resolveQmkPin falls
// back to the label); unset pins become NO_PIN. Returns the extra diagnostics.
function qmkConfigH(config: ConfigKeymap): {
    content: string
    diagnostics: Diagnostic[]
} {
    const board = resolveController(config).board
    const pins = config.keyboard.pins
    const diagnostics: Diagnostic[] = []
    const lines = [`#pragma once`, `// remappr keymap — generated pin map.`]

    if (pins && pins.rows.length && pins.cols.length) {
        const rows = pins.rows.map((p) => resolveQmkPin(board, p)).join(', ')
        const cols = pins.cols.map((p) => resolveQmkPin(board, p)).join(', ')
        lines.push(
            `#define MATRIX_ROW_PINS { ${rows} }`,
            `#define MATRIX_COL_PINS { ${cols} }`,
            `// diode-direction assumed COL2ROW — verify against your wiring.`,
            `#define DIODE_DIRECTION COL2ROW`,
        )
    } else {
        const keyPins = config.keyboard.keys.map((k) => k.pin?.trim() ?? '')
        if (keyPins.some((p) => p)) {
            const tokens = keyPins.map((p) =>
                p ? resolveQmkPin(board, p) : 'NO_PIN',
            )
            lines.push(
                `// DIRECT_PINS as a single row — reshape into your MATRIX_ROWS×MATRIX_COLS grid.`,
                `#define DIRECT_PINS {{ ${tokens.join(', ')} }}`,
            )
            diagnostics.push({
                level: 'warn',
                message:
                    'DIRECT_PINS emitted as a single row; reshape into your MATRIX_ROWS×MATRIX_COLS grid in config.h',
                path: ['keyboard', 'keys'],
            })
            if (keyPins.some((p) => !p))
                diagnostics.push({
                    level: 'warn',
                    message:
                        'some keys have no pin assigned — emitted as NO_PIN in DIRECT_PINS',
                    path: ['keyboard', 'keys'],
                })
        } else {
            lines.push(`// add #defines here`)
        }
    }
    return { content: lines.join('\n') + '\n', diagnostics }
}

function qmkBundle(config: ConfigKeymap, target: Target): ProjectBundle {
    const kb = sanitize(config.keyboard.id || config.meta.name)
    const km = 'remappr'
    const { files: compiled, diagnostics } = getCompiler(target).compile(config)
    const keymapC = compiled.find((f) => f.filename.endsWith('.c'))
    const base = `keyboards/${kb}/keymaps/${km}`
    const configH = qmkConfigH(config)

    const qmkJson = JSON.stringify(
        { userspace_version: '1.1', build_targets: [[kb, km]] },
        null,
        2,
    )

    const readme = [
        `# ${config.meta.name} — QMK userspace`,
        ``,
        `Generated by remappr as a \`qmk_userspace\` skeleton.`,
        ``,
        `## Build in the cloud`,
        `1. Push these files to a GitHub repo (a fork of \`qmk/qmk_userspace\` works).`,
        `2. The included workflow builds the keymap on every push.`,
        `3. Download the firmware artifact from the Actions run.`,
        ``,
        `## Build locally`,
        `\`\`\`sh`,
        `qmk userspace-compile`,
        `# or: qmk compile -kb ${kb} -km ${km}`,
        `\`\`\``,
        ``,
        `## Notes`,
        `- The keyboard \`${kb}\` must exist in QMK (in-tree or added under`,
        `  \`keyboards/${kb}/\` with its own \`info.json\`). remappr emits the keymap,`,
        `  not a full keyboard definition.`,
        ``,
    ].join('\n')

    const files: ExportedFile[] = [
        text(`${base}/keymap.c`, keymapC ? asText(keymapC.content) : ''),
        text(
            `${base}/rules.mk`,
            `# remappr keymap — add feature toggles here\n`,
        ),
        text(`${base}/config.h`, configH.content),
        text(`qmk.json`, qmkJson + '\n'),
        text(`.github/workflows/build_binaries.yml`, QMK_BUILD_WORKFLOW),
        text(`README.md`, readme),
    ]

    return {
        files,
        diagnostics: [...diagnostics, ...configH.diagnostics],
        rootName: `${kb}-qmk-userspace`,
    }
}

/** Build the full project bundle for a target. ZMK → zmk-config skeleton;
 *  QMK/Keychron → qmk_userspace skeleton. */
export function buildProjectBundle(
    config: ConfigKeymap,
    target: Target,
): ProjectBundle {
    return target === 'zmk' ? zmkBundle(config) : qmkBundle(config, target)
}
