// Pattern check: Strategy (Tier 1) — extended — concrete ZMK KeymapCompiler registered into the Strategy registry in compiler.ts.
//
// Emits a ZMK .keymap devicetree overlay directly from the canonical config.
// Behavior coverage tracks https://zmk.dev/docs/keymaps/behaviors. Anything a
// ZMK board can't express (per_key lighting, macro `text` steps, tap-dance
// `hold`) emits a `warn` diagnostic and degrades to a safe binding rather than
// producing broken devicetree.

import type { ExportedFile } from '../../types'
import type { DiagnosticBag } from '../diagnostics'
import { runCompile, registerCompiler, type KeymapCompiler } from '../compiler'
import { ZMK_MOD, ZMK_MOD_FN, zmkKeyName } from '../names'
import type {
    CanonAction,
    CanonKeyPress,
    CanonMacro,
    CanonModMorph,
    CanonTapDance,
    ConfigKeymap,
    LightingAction,
} from '../types'
import type { Modifier } from '../keycodes'

const RGB_UG: Partial<Record<LightingAction, string>> = {
    toggle: 'RGB_TOG',
    on: 'RGB_ON',
    off: 'RGB_OFF',
    brightness_up: 'RGB_BRI',
    brightness_down: 'RGB_BRD',
    hue_up: 'RGB_HUI',
    hue_down: 'RGB_HUD',
    saturation_up: 'RGB_SAI',
    saturation_down: 'RGB_SAD',
    effect_next: 'RGB_EFF',
    effect_previous: 'RGB_EFR',
    speed_up: 'RGB_SPI',
    speed_down: 'RGB_SPD',
}
const BL: Partial<Record<LightingAction, string>> = {
    toggle: 'BL_TOG',
    on: 'BL_ON',
    off: 'BL_OFF',
    brightness_up: 'BL_INC',
    brightness_down: 'BL_DEC',
    cycle: 'BL_CYCLE',
}

const EP: Record<'toggle' | 'on' | 'off', string> = {
    toggle: 'EP_TOG',
    on: 'EP_ON',
    off: 'EP_OFF',
}
const MOUSE_BTN: Record<string, string> = {
    left: 'MB1',
    right: 'MB2',
    middle: 'MB3',
    mb4: 'MB4',
    mb5: 'MB5',
}
const MOVE: Record<string, string> = {
    up: 'MOVE_UP',
    down: 'MOVE_DOWN',
    left: 'MOVE_LEFT',
    right: 'MOVE_RIGHT',
}
const SCRL: Record<string, string> = {
    up: 'SCRL_UP',
    down: 'SCRL_DOWN',
    left: 'SCRL_LEFT',
    right: 'SCRL_RIGHT',
}

const sanitize = (id: string): string => id.replace(/[^a-zA-Z0-9_]/g, '_')

// ZMK modifier bitmask flags (dt-bindings/zmk/modifiers.h) for mod-morph `mods`.
const MOD_FLAG: Record<Modifier, string> = {
    LEFT_CTRL: 'MOD_LCTL',
    LEFT_SHIFT: 'MOD_LSFT',
    LEFT_ALT: 'MOD_LALT',
    LEFT_GUI: 'MOD_LGUI',
    RIGHT_CTRL: 'MOD_RCTL',
    RIGHT_SHIFT: 'MOD_RSFT',
    RIGHT_ALT: 'MOD_RALT',
    RIGHT_GUI: 'MOD_RGUI',
}
const modFlags = (mods: Modifier[]): string =>
    `(${mods.map((m) => MOD_FLAG[m]).join('|')})`

// Board-hardware nodes remappr cannot derive from a keymap/geometry — the ZMK
// connection never exposes them. Emitted as a checklist comment so the file is
// a clear skeleton: the user pastes the real nodes from their board/shield.
const NOT_GENERATED_BLOCK: string[] = [
    `/* ─────────────────────────────────────────────────────────────────────`,
    ` * NOT GENERATED by remappr — board-specific hardware, add from your`,
    ` * board/shield overlay (these are wiring, not keymap; ZMK does not`,
    ` * expose them over the Studio connection):`,
    ` *`,
    ` *   • kscan          — matrix/direct GPIO scan + row/col gpios`,
    ` *   • chosen         — zmk,kscan / zmk,physical-layout / zmk,matrix-transform`,
    ` *   • pinctrl / pins — SoC pin assignments`,
    ` *   • &gpio / diode-direction, debounce timings`,
    ` *   • underglow / backlight / RGB LED drivers (e.g. &led_strip)`,
    ` *   • encoders (EC11 sensors) + sensor-channel wiring`,
    ` *   • power / battery / ext-power control nodes`,
    ` *   • display, pointing device, or other peripheral nodes`,
    ` *`,
    ` * Also re-check the matrix-transform RC() map above against your real`,
    ` * kscan — it is derived from physical position, not electrical wiring.`,
    ` * ───────────────────────────────────────────────────────────────────── */`,
]

interface Ctx {
    layerIndex: Map<string, number>
    diag: DiagnosticBag
}

function kp(kpAction: CanonKeyPress): string {
    let token = zmkKeyName(kpAction.key)
    // Wrap modifiers innermost-last: LC(LS(A)).
    for (const m of kpAction.mods ?? []) token = `${ZMK_MOD_FN[m]}(${token})`
    return `&kp ${token}`
}

function emitBinding(
    a: CanonAction,
    ctx: Ctx,
    path: (string | number)[],
): string {
    const layerIdx = (name: string): number => {
        const i = ctx.layerIndex.get(name)
        if (i === undefined) {
            ctx.diag.error(`unknown layer "${name}"`, path)
            return 0
        }
        return i
    }
    switch (a.type) {
        case 'key_press':
            return kp(a)
        case 'tap_hold':
            return a.hold.type === 'modifier'
                ? `&mt ${ZMK_MOD[a.hold.modifier]} ${zmkKeyName(a.tap.key)}`
                : `&lt ${layerIdx(a.hold.layer)} ${zmkKeyName(a.tap.key)}`
        case 'layer':
            return a.mode === 'momentary'
                ? `&mo ${layerIdx(a.layer)}`
                : a.mode === 'toggle'
                  ? `&tog ${layerIdx(a.layer)}`
                  : a.mode === 'to'
                    ? `&to ${layerIdx(a.layer)}`
                    : `&sl ${layerIdx(a.layer)}`
        case 'sticky_key':
            return `&sk ${zmkKeyName(a.key)}`
        case 'caps_word':
            return '&caps_word'
        case 'transparent':
            return '&trans'
        case 'none':
            return '&none'
        case 'bootloader':
            return '&bootloader'
        case 'reset':
            return '&sys_reset'
        case 'output':
            if (a.action === 'usb') return '&out OUT_USB'
            if (a.action === 'toggle') return '&out OUT_TOG'
            if (a.action === 'none') return '&out OUT_NONE'
            if (a.action === 'bluetooth_clear') return '&bt BT_CLR'
            if (a.action === 'bluetooth_next') return '&bt BT_NXT'
            if (a.action === 'bluetooth_prev') return '&bt BT_PRV'
            if (a.action === 'bluetooth_disconnect')
                return `&bt BT_DISC ${a.profile ?? 0}`
            return a.profile !== undefined
                ? `&bt BT_SEL ${a.profile}`
                : '&out OUT_BLE'
        case 'lighting': {
            if (a.target === 'per_key') {
                ctx.diag.warn(
                    'per_key lighting is not available on ZMK; emitted &none',
                    path,
                )
                return '&none'
            }
            if (a.target === 'backlight') {
                const t = BL[a.action]
                if (!t) {
                    ctx.diag.warn(
                        `backlight has no "${a.action}" action on ZMK; emitted &none`,
                        path,
                    )
                    return '&none'
                }
                return `&bl ${t}`
            }
            return `&rgb_ug ${RGB_UG[a.action] ?? 'RGB_TOG'}`
        }
        case 'macro':
            return a.param !== undefined
                ? `&${sanitize(a.ref)} ${zmkKeyName(a.param)}`
                : `&${sanitize(a.ref)}`
        case 'tap_dance':
            return `&${sanitize(a.ref)}`
        case 'mod_morph':
            return `&${sanitize(a.ref)}`
        case 'soft_off':
            return '&soft_off'
        case 'studio_unlock':
            return '&studio_unlock'
        case 'grave_escape':
            return '&gresc'
        case 'key_repeat':
            return '&key_repeat'
        case 'key_toggle':
            return `&kt ${zmkKeyName(a.key)}`
        case 'ext_power':
            return `&ext_power ${EP[a.action]}`
        case 'mouse_key':
            return `&mkp ${MOUSE_BTN[a.button]}`
        case 'mouse_move':
            return `&mmv ${MOVE[a.direction]}`
        case 'mouse_scroll':
            return `&msc ${SCRL[a.direction]}`
    }
}

function emitMacros(macros: CanonMacro[], ctx: Ctx): string[] {
    const out: string[] = []
    out.push('    macros {')
    for (const m of macros) {
        const bindings: string[] = []
        for (const s of m.steps) {
            if (s.type === 'press')
                bindings.push(`<&macro_press &kp ${zmkKeyName(s.key)}>`)
            else if (s.type === 'release')
                bindings.push(`<&macro_release &kp ${zmkKeyName(s.key)}>`)
            else if (s.type === 'tap')
                bindings.push(`<&macro_tap &kp ${zmkKeyName(s.key)}>`)
            else if (s.type === 'wait')
                bindings.push(`<&macro_wait_time ${s.ms}>`)
            else if (s.type === 'tap_time')
                bindings.push(`<&macro_tap_time ${s.ms}>`)
            else if (s.type === 'param')
                bindings.push(
                    `<&macro_tap &macro_param_${s.from ?? 1}to${s.to ?? 1}>`,
                )
            else if (s.type === 'pause_for_release')
                bindings.push(`<&macro_pause_for_release>`)
            else
                ctx.diag.warn(
                    `macro "${m.id}" text steps are not generated for ZMK`,
                    ['macros'],
                )
        }
        // #binding-cells: explicit `params`, else inferred from param steps
        // (highest `from` used). 0 = plain, 1 = one-param, 2 = two-param.
        const inferredCells = m.steps.reduce(
            (n, s) => (s.type === 'param' ? Math.max(n, s.from ?? 1) : n),
            0,
        )
        const cells = m.params ?? inferredCells
        const suffix =
            cells === 2 ? '-two-param' : cells === 1 ? '-one-param' : ''
        // A stub (no emittable steps) gets an inert &none + a visible TODO, so
        // the node is valid devicetree instead of an empty `bindings = ;`.
        const isStub = bindings.length === 0
        out.push(`        ${sanitize(m.id)}: ${sanitize(m.id)} {`)
        out.push(`            compatible = "zmk,behavior-macro${suffix}";`)
        out.push(`            #binding-cells = <${cells}>;`)
        if (isStub) {
            out.push(
                `            /* TODO: stub — restore this macro's steps from your board source. */`,
            )
            bindings.push('<&none>')
        }
        out.push(`            bindings = ${bindings.join(', ')};`)
        out.push(`        };`)
    }
    out.push('    };')
    return out
}

// Encoders → ZMK `sensor-bindings`. A keypress/keypress pair uses the built-in
// `&inc_dec_kp`; any other behavior pair needs a generated
// `zmk,behavior-sensor-rotate` node (referenced as `&sr_<layer>_<enc>`). The
// encoder PRESS action is a normal matrix key in ZMK (not a sensor binding), so
// it cannot live here — warned once. Returns the behavior-node lines plus the
// per-layer `sensor-bindings` value to splice into each layer node.
function emitEncoderSensors(
    config: ConfigKeymap,
    ctx: Ctx,
): { behaviorLines: string[]; byLayer: Map<number, string> } {
    const behaviorLines: string[] = []
    const byLayer = new Map<number, string>()
    let warnedPress = false

    config.layers.forEach((layer, li) => {
        if (!layer.encoders?.length) return
        const tokens: string[] = []
        layer.encoders.forEach((e, ei) => {
            if (e.press && !warnedPress) {
                ctx.diag.warn(
                    'encoder press is a regular matrix key in ZMK, not a sensor binding; place it in the layer bindings instead',
                    ['layers', li, 'encoders', ei, 'press'],
                )
                warnedPress = true
            }
            if (e.cw.type === 'key_press' && e.ccw.type === 'key_press') {
                tokens.push(
                    `&inc_dec_kp ${zmkKeyName(e.cw.key)} ${zmkKeyName(e.ccw.key)}`,
                )
                return
            }
            // Generate a sensor-rotate node for the non-keypress pair.
            const id = `sr_${li}_${ei}`
            const cw = emitBinding(e.cw, ctx, [
                'layers',
                li,
                'encoders',
                ei,
                'cw',
            ])
            const ccw = emitBinding(e.ccw, ctx, [
                'layers',
                li,
                'encoders',
                ei,
                'ccw',
            ])
            behaviorLines.push(
                `        ${id}: ${id} {`,
                `            compatible = "zmk,behavior-sensor-rotate";`,
                `            #sensor-binding-cells = <0>;`,
                `            bindings = <${cw}>, <${ccw}>;`,
                `        };`,
            )
            tokens.push(`&${id}`)
        })
        byLayer.set(li, tokens.join(' '))
    })

    return { behaviorLines, byLayer }
}

function emitModMorphs(morphs: CanonModMorph[], ctx: Ctx): string[] {
    const out: string[] = ['    behaviors {']
    for (const mm of morphs) {
        const id = sanitize(mm.id)
        const b0 = emitBinding(mm.bindings[0], ctx, ['modMorphs', mm.id, 0])
        const b1 = emitBinding(mm.bindings[1], ctx, ['modMorphs', mm.id, 1])
        out.push(
            `        ${id}: ${id} {`,
            `            compatible = "zmk,behavior-mod-morph";`,
            `            #binding-cells = <0>;`,
            `            bindings = <${b0}>, <${b1}>;`,
            `            mods = <${modFlags(mm.mods)}>;`,
        )
        if (mm.keepMods?.length)
            out.push(`            keep-mods = <${modFlags(mm.keepMods)}>;`)
        out.push(`        };`)
    }
    out.push('    };')
    return out
}

function emitTapDances(tds: CanonTapDance[], ctx: Ctx): string[] {
    const out: string[] = []
    out.push('    behaviors {')
    for (const td of tds) {
        if (td.hold) {
            ctx.diag.warn(
                `tap-dance "${td.id}" hold action is not representable in a ZMK tap-dance; dropped`,
                ['tapDances'],
            )
        }
        const bindings = [...td.taps]
            .sort((a, b) => a.count - b.count)
            .map((t) => `<${emitBinding(t.action, ctx, ['tapDances'])}>`)
        out.push(`        ${sanitize(td.id)}: ${sanitize(td.id)} {`)
        out.push(`            compatible = "zmk,behavior-tap-dance";`)
        out.push(`            #binding-cells = <0>;`)
        if (td.tappingTermMs !== undefined)
            out.push(`            tapping-term-ms = <${td.tappingTermMs}>;`)
        out.push(`            bindings = ${bindings.join(', ')};`)
        out.push(`        };`)
    }
    out.push('    };')
    return out
}

// Dense-rank distinct values to contiguous indices (0,1,2,…). Raw position can
// skip values (a vertical gap, a split half), which would leave holes in the
// matrix; ranking collapses each distinct row/column line to one matrix index.
function denseRank(values: number[]): Map<number, number> {
    const sorted = [...new Set(values)].sort((a, b) => a - b)
    return new Map(sorted.map((v, i) => [v, i]))
}

// Derive a `zmk,matrix-transform` from the physical geometry by dense-ranking
// distinct y → row and distinct x → col, so the matrix is contiguous (no gaps).
// The REAL row/col is the board's kscan wiring, which ZMK does not expose over
// the connection — so this is a position-derived scaffold, not the true
// electrical matrix. The map order matches the keymap binding order
// (physical-layout key order), which is what ZMK requires.
function emitMatrixTransform(
    config: ConfigKeymap,
    diag: DiagnosticBag,
): { lines: string[]; label: string } {
    const rowRank = denseRank(config.keyboard.keys.map((k) => Math.round(k.y)))
    const colRank = denseRank(config.keyboard.keys.map((k) => Math.round(k.x)))
    const cells = config.keyboard.keys.map((k) => ({
        row: rowRank.get(Math.round(k.y)) ?? 0,
        col: colRank.get(Math.round(k.x)) ?? 0,
    }))
    const rows = rowRank.size
    const columns = colRank.size

    diag.warn(
        'matrix-transform RC() values are derived from physical key position, ' +
            'not the board kscan wiring (ZMK does not expose it over the ' +
            'connection). Verify/replace them against your board before flashing.',
        ['keyboard', 'keys'],
    )

    // One line per matrix row: break whenever the row index changes (keymap
    // order is row-major for the common case), mirroring a hand-written map.
    const lines: string[] = []
    let current = -1
    let line: string[] = []
    const flush = (): void => {
        if (line.length) lines.push('            ' + line.join(' '))
        line = []
    }
    for (const c of cells) {
        if (c.row !== current) {
            flush()
            current = c.row
        }
        line.push(`RC(${c.row},${c.col})`)
    }
    flush()

    return {
        label: 'default_transform',
        lines: [
            `    default_transform: keymap_transform_0 {`,
            `        compatible = "zmk,matrix-transform";`,
            `        /* DERIVED from key geometry — confirm against your kscan. */`,
            `        columns = <${columns}>;`,
            `        rows = <${rows}>;`,
            `        map = <`,
            ...lines,
            `        >;`,
            `    };`,
        ],
    }
}

// Emit the `zmk,physical-layout` node from the config geometry, plus a
// geometry-derived `zmk,matrix-transform` the physical-layout points at. The
// remaining hardware nodes (kscan / pinctrl / LED drivers) are board-specific
// and intentionally NOT generated — they live in the board's own overlay.
function emitOverlay(config: ConfigKeymap, diag: DiagnosticBag): ExportedFile {
    const cu = (n: number): number => Math.round(n * 100) // key units -> centi-units
    const keyLines = config.keyboard.keys.map((k, i) => {
        const attrs =
            `<&key_physical_attrs ${cu(k.w)} ${cu(k.h)} ${cu(k.x)} ${cu(k.y)} ` +
            `${cu(k.r)} ${cu(k.rx ?? 0)} ${cu(k.ry ?? 0)}>`
        return `            ${i === 0 ? '=' : ','} ${attrs}`
    })

    const transform = emitMatrixTransform(config, diag)

    const lines = [
        `/* Generated by remappr — ZMK physical layout for ${config.keyboard.name}.`,
        ` * Key geometry + a geometry-DERIVED matrix-transform are generated.`,
        ` * Remaining hardware nodes (kscan, pinctrl, backlight/underglow`,
        ` * drivers) are board-specific — keep them in your board/shield overlay.`,
        ` * The matrix-transform RC() map is a scaffold from physical position,`,
        ` * NOT the real kscan wiring — verify it before flashing. */`,
        `#include <physical_layouts.dtsi>`,
        `#include <dt-bindings/zmk/matrix_transform.h>`,
        ``,
        `/ {`,
        `    physical_layout_default: physical_layout_default {`,
        `        compatible = "zmk,physical-layout";`,
        `        display-name = "${config.keyboard.name}";`,
        `        transform = <&${transform.label}>;`,
        `        keys`,
        ...keyLines,
        `            ;`,
        `    };`,
        ``,
        ...transform.lines,
        `};`,
        ``,
        ...NOT_GENERATED_BLOCK,
        ``,
    ]
    return {
        filename: `${sanitize(config.keyboard.id || config.keyboard.name)}.overlay`,
        mime: 'text/plain',
        content: lines.join('\n'),
    }
}

function emitKeymap(config: ConfigKeymap, diag: DiagnosticBag): ExportedFile[] {
    const ctx: Ctx = {
        layerIndex: new Map(config.layers.map((l, i) => [l.name, i])),
        diag,
    }

    const lines: string[] = []
    lines.push(
        `/* Generated by remappr — ZMK keymap for ${config.keyboard.name}.`,
        ` * Keymap layers, behaviors, combos, macros and tap-dances only.`,
        ` * Physical layout + matrix-transform live in the .overlay; board`,
        ` * hardware (kscan, pinctrl, LED drivers, …) is NOT generated — see`,
        ` * the "NOT GENERATED" checklist in the .overlay. */`,
    )
    lines.push(`#include <behaviors.dtsi>`)
    lines.push(`#include <dt-bindings/zmk/keys.h>`)
    lines.push(`#include <dt-bindings/zmk/bt.h>`)
    lines.push(`#include <dt-bindings/zmk/outputs.h>`)
    lines.push(`#include <dt-bindings/zmk/rgb.h>`)
    lines.push(`#include <dt-bindings/zmk/backlight.h>`)
    lines.push(`#include <dt-bindings/zmk/ext_power.h>`)
    lines.push(`#include <dt-bindings/zmk/pointing.h>`)
    lines.push(``)
    lines.push(`/ {`)

    if (config.macros?.length) lines.push(...emitMacros(config.macros, ctx), ``)
    if (config.tapDances?.length)
        lines.push(...emitTapDances(config.tapDances, ctx), ``)
    if (config.modMorphs?.length)
        lines.push(...emitModMorphs(config.modMorphs, ctx), ``)

    // Encoders: build sensor-rotate behavior nodes (non-keypress pairs) up front,
    // then reference them per layer below.
    const encoders = emitEncoderSensors(config, ctx)
    if (encoders.behaviorLines.length) {
        lines.push(`    behaviors {`, ...encoders.behaviorLines, `    };`, ``)
    }

    // combos
    if (config.combos?.length) {
        lines.push(`    combos {`)
        lines.push(`        compatible = "zmk,combos";`)
        config.combos.forEach((c, ci) => {
            const binding = emitBinding(c.action, ctx, ['combos', ci, 'action'])
            const layersAttr = c.layers?.length
                ? `\n            layers = <${c.layers.map((n) => ctx.layerIndex.get(n) ?? 0).join(' ')}>;`
                : ''
            lines.push(`        combo_${sanitize(c.name)} {`)
            if (c.timeoutMs !== undefined)
                lines.push(`            timeout-ms = <${c.timeoutMs}>;`)
            lines.push(`            key-positions = <${c.keys.join(' ')}>;`)
            lines.push(`            bindings = <${binding}>;${layersAttr}`)
            lines.push(`        };`)
        })
        lines.push(`    };`)
        lines.push(``)
    }

    // conditional layers
    if (config.conditionalLayers?.length) {
        const idx = (name: string): number => {
            const i = ctx.layerIndex.get(name)
            if (i === undefined) {
                diag.error(`unknown layer "${name}"`, ['conditionalLayers'])
                return 0
            }
            return i
        }
        lines.push(`    conditional_layers {`)
        lines.push(`        compatible = "zmk,conditional-layers";`)
        config.conditionalLayers.forEach((cl, ci) => {
            lines.push(`        cond_${ci} {`)
            lines.push(
                `            if-layers = <${cl.ifLayers.map(idx).join(' ')}>;`,
            )
            lines.push(`            then-layer = <${idx(cl.thenLayer)}>;`)
            lines.push(`        };`)
        })
        lines.push(`    };`)
        lines.push(``)
    }

    // keymap
    lines.push(`    keymap {`)
    lines.push(`        compatible = "zmk,keymap";`)
    config.layers.forEach((layer, li) => {
        const cells = layer.bindings.map((b, bi) =>
            emitBinding(b, ctx, ['layers', li, 'bindings', bi]),
        )
        const wrapped: string[] = []
        for (let i = 0; i < cells.length; i += 6) {
            wrapped.push('                ' + cells.slice(i, i + 6).join(' '))
        }
        lines.push(`        layer_${sanitize(layer.name)} {`)
        lines.push(`            display-name = "${layer.name}";`)
        lines.push(`            bindings = <`)
        lines.push(wrapped.join('\n'))
        lines.push(`            >;`)
        // encoders -> sensor-bindings (inc_dec_kp for keypress pairs, generated
        // sensor-rotate nodes for anything else — see emitEncoderSensors)
        const sensorBindings = encoders.byLayer.get(li)
        if (sensorBindings) {
            lines.push(`            sensor-bindings = <${sensorBindings}>;`)
        }
        lines.push(`        };`)
    })
    lines.push(`    };`)
    lines.push(`};`)
    lines.push(``)

    return [
        {
            filename: `${sanitize(config.keyboard.id || config.keyboard.name)}.keymap`,
            mime: 'text/plain',
            content: lines.join('\n'),
        },
        emitOverlay(config, diag),
    ]
}

export const zmkCompiler: KeymapCompiler = {
    target: 'zmk',
    compile: (config) => runCompile(config, emitKeymap),
}

registerCompiler(zmkCompiler)
