// Pattern check: no GoF pattern (-) — rejected — static page metadata + simple grouping helper, no abstraction.
import {
    AC_ENTRIES,
    AL_ENTRIES,
    AUDIO_ENTRIES,
    BACKLIGHT_ENTRIES,
    CONSUMER_ENTRIES,
    CONTACT_ENTRIES,
    JOYSTICK_ENTRIES,
    KEYBOARD_ENTRIES,
    MACROS_ENTRIES,
    MAGIC_ENTRIES,
    MEDIA_ENTRIES,
    MEDIA_TRANSPORT_ENTRIES,
    MIDI_ENTRIES,
    MISC_ENTRIES,
    MOD_ENTRIES,
    MOUSE_ENTRIES,
    OS_KEYS_ENTRIES,
    PROGRAMMABLE_ENTRIES,
    QUANTUM_ENTRIES,
    RGB_ENTRIES,
    SHIFTED_ENTRIES,
    WIRELESS_ENTRIES,
} from './entries'
import type {CanonicalKeyId, CatalogPage} from './types'

// PR 1 ships HID pages only. PR 2 adds 'wireless' / 'os-keys' / 'rgb' /
// 'backlight' / 'audio' / 'mouse' / 'midi' / 'magic' / 'quantum' /
// 'macros' / 'misc' once per-firmware codecs and canonical entries land.
export const CATALOG_PAGES: CatalogPage[] = [
    {
        id: 'keyboard',
        name: 'Keyboard',
        style: 'keyboard-grid',
        visible: true,
        entries: [...KEYBOARD_ENTRIES, ...SHIFTED_ENTRIES, ...MOD_ENTRIES],
    },
    {
        id: 'consumer',
        name: 'Consumer',
        style: 'flat-grid',
        visible: true,
        entries: CONSUMER_ENTRIES,
    },
    {
        id: 'ac',
        name: 'AC',
        style: 'flat-grid',
        visible: true,
        entries: AC_ENTRIES,
    },
    {
        id: 'al',
        name: 'AL',
        style: 'flat-grid',
        visible: true,
        entries: AL_ENTRIES,
    },
    {
        id: 'contact',
        name: 'Contact',
        style: 'flat-grid',
        visible: true,
        entries: CONTACT_ENTRIES,
    },
    {
        id: 'media',
        name: 'Media',
        style: 'flat-grid',
        visible: true,
        entries: [...MEDIA_ENTRIES, ...MEDIA_TRANSPORT_ENTRIES],
    },
    {
        id: 'wireless',
        name: 'Wireless',
        style: 'flat-grid',
        visible: true,
        entries: WIRELESS_ENTRIES,
    },
    {
        id: 'os-keys',
        name: 'OS Keys',
        style: 'flat-grid',
        visible: true,
        entries: OS_KEYS_ENTRIES,
    },
    {
        id: 'rgb',
        name: 'RGB',
        style: 'flat-grid',
        visible: true,
        entries: RGB_ENTRIES,
    },
    {
        id: 'backlight',
        name: 'Backlight',
        style: 'flat-grid',
        visible: true,
        entries: BACKLIGHT_ENTRIES,
    },
    {
        id: 'audio',
        name: 'Audio',
        style: 'flat-grid',
        visible: true,
        entries: AUDIO_ENTRIES,
    },
    {
        id: 'mouse',
        name: 'Mouse',
        style: 'flat-grid',
        visible: true,
        entries: MOUSE_ENTRIES,
    },
    {
        id: 'magic',
        name: 'Magic',
        style: 'flat-grid',
        visible: true,
        entries: MAGIC_ENTRIES,
    },
    {
        id: 'quantum',
        name: 'Quantum',
        style: 'flat-grid',
        visible: true,
        entries: QUANTUM_ENTRIES,
    },
    {
        id: 'macros',
        name: 'Macros',
        style: 'flat-grid',
        visible: true,
        entries: MACROS_ENTRIES,
    },
    {
        id: 'misc',
        name: 'Misc',
        style: 'flat-grid',
        visible: true,
        entries: [
            ...MISC_ENTRIES,
            ...JOYSTICK_ENTRIES,
            ...PROGRAMMABLE_ENTRIES,
        ],
    },
    {
        id: 'midi',
        name: 'MIDI',
        style: 'flat-grid',
        visible: true,
        entries: MIDI_ENTRIES,
    },
]

// Maps a canonical id prefix → page id. Codecs can add new prefixes by
// extending this map at module init.
const PREFIX_TO_PAGE: Record<string, string> = {
    key: 'keyboard',
    consumer: 'consumer',
    ac: 'ac',
    al: 'al',
    media: 'media',
    contact: 'contact',
    wireless: 'wireless',
    os: 'os-keys',
    rgb: 'rgb',
    backlight: 'backlight',
    led_matrix: 'backlight',
    audio: 'audio',
    mouse: 'mouse',
    midi: 'midi',
    magic: 'magic',
    macro: 'macros',
    system: 'quantum',
    mod: 'keyboard',
    display: 'misc',
    caps_word: 'misc',
    leader: 'misc',
    key_lock: 'misc',
    layer_lock: 'misc',
    repeat: 'misc',
    auto_shift: 'misc',
    autocorrect: 'misc',
    grave_escape: 'misc',
    space_cadet: 'misc',
    swap_hands: 'misc',
    tap_term: 'misc',
    joystick: 'misc',
    programmable: 'misc',
    one_shot: 'misc',
    unicode: 'misc',
    tri_layer: 'misc',
    haptic: 'misc',
    combo: 'misc',
    velocikey: 'misc',
    key_override: 'misc',
    secure: 'misc',
}

export const groupForId = ( id: CanonicalKeyId ): string | null => {
    const prefix = id.split( '.' )[0]
    return PREFIX_TO_PAGE[prefix] ?? null
}
