import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import {
    getCompiler,
    hasCompiler,
    parseKeymap,
    serializeKeymap,
} from '../index'

const seed = readFileSync(
    fileURLToPath(new URL('../../mock/seed.keymap.json', import.meta.url)),
    'utf8',
)
const config = parseKeymap(seed)

describe('keymap compilers', () => {
    it('registers all three targets', () => {
        expect(hasCompiler('zmk')).toBe(true)
        expect(hasCompiler('qmk')).toBe(true)
        expect(hasCompiler('keychron')).toBe(true)
    })

    it('compiles a ZMK .keymap with the expected behaviors', () => {
        const { files, diagnostics } = getCompiler('zmk').compile(config)
        // keymap + physical-layout overlay
        expect(files).toHaveLength(2)
        const keymap = files.find((f) => f.filename.endsWith('.keymap'))!
        const dts = String(keymap.content)
        expect(dts).toContain('compatible = "zmk,keymap"')
        expect(dts).toContain('&kp Q')
        expect(dts).toContain('&kp LC(C)') // "Ctrl+C" combo string
        expect(dts).toContain('&lt 1') // layer_tap -> lower (index 1)
        expect(dts).toContain('&mt LSHFT') // mod_tap -> Left Shift
        expect(dts).toContain('&mo 2') // momentary adjust (index 2)
        expect(dts).toContain('&bt BT_SEL 0')
        expect(dts).toContain('&rgb_ug RGB_TOG')
        expect(dts).toContain('combo_esc')
        expect(dts).toContain('zmk,behavior-macro')
        expect(dts).toContain('zmk,behavior-tap-dance')
        expect(dts).toContain('&inc_dec_kp') // encoder
        // per_key lighting is unsupported on ZMK -> warn
        expect(
            diagnostics.some(
                (d) => d.level === 'warn' && /per_key/.test(d.message),
            ),
        ).toBe(true)
    })

    it('compiles a QMK keymap.c with the expected keycodes', () => {
        const { files, diagnostics } = getCompiler('qmk').compile(config)
        const c = String(files[0].content)
        expect(files[0].filename).toBe('keymap.c')
        expect(c).toContain('const uint16_t PROGMEM keymaps')
        expect(c).toContain('MO(2)')
        expect(c).toContain('LT(1,')
        expect(c).toContain('LSFT_T(')
        expect(c).toContain('LCTL(') // Ctrl+C
        expect(c).toContain('RGB_MOD') // per_key effect_next is fine on QMK
        // bluetooth output has no standard QMK keycode -> warn
        expect(
            diagnostics.some(
                (d) =>
                    d.level === 'warn' && /output "bluetooth"/.test(d.message),
            ),
        ).toBe(true)
    })

    it('Keychron allows bluetooth output (no output warning)', () => {
        const { diagnostics } = getCompiler('keychron').compile(config)
        expect(
            diagnostics.some((d) => /output "bluetooth"/.test(d.message)),
        ).toBe(false)
    })

    it('emits a ZMK physical-layout .overlay from the geometry', () => {
        const { files } = getCompiler('zmk').compile(config)
        const overlay = files.find((f) => f.filename.endsWith('.overlay'))!
        const o = String(overlay.content)
        expect(o).toContain('#include <physical_layouts.dtsi>')
        expect(o).toContain('compatible = "zmk,physical-layout"')
        expect(o).toContain('&key_physical_attrs')
        // 36 keys -> 36 key_physical_attrs entries
        expect(o.match(/&key_physical_attrs/g)).toHaveLength(36)
    })

    it('emits a geometry-derived matrix-transform wired to the physical-layout', () => {
        const { files, diagnostics } = getCompiler('zmk').compile(config)
        const overlay = files.find((f) => f.filename.endsWith('.overlay'))!
        const o = String(overlay.content)
        expect(o).toContain('#include <dt-bindings/zmk/matrix_transform.h>')
        expect(o).toContain('compatible = "zmk,matrix-transform"')
        expect(o).toContain('transform = <&default_transform>;')
        // one RC() per key, in keymap order
        expect(o.match(/RC\(\d+,\d+\)/g)).toHaveLength(36)
        // honest about the derivation
        expect(
            diagnostics.some((d) => /matrix-transform RC/.test(d.message)),
        ).toBe(true)
    })

    it('lists non-generated board hardware as a checklist in both files', () => {
        const { files } = getCompiler('zmk').compile(config)
        const overlay = String(
            files.find((f) => f.filename.endsWith('.overlay'))!.content,
        )
        expect(overlay).toContain('NOT GENERATED by remappr')
        expect(overlay).toContain('kscan')
        expect(overlay).toContain('pinctrl')
        const keymap = String(
            files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(keymap).toContain('NOT GENERATED')
    })
})

// A config exercising every behavior added for real-ZMK-config parity.
const EXTRA = `{
    "schemaVersion": 1,
    "kind": "remappr.keymap",
    "meta": { "name": "Extra", "target": null },
    "keyboard": { "id": "extra", "name": "Extra", "keys": [
        {"x":0,"y":0},{"x":1,"y":0},{"x":2,"y":0},{"x":3,"y":0},
        {"x":0,"y":1},{"x":1,"y":1},{"x":2,"y":1},{"x":3,"y":1},
        {"x":0,"y":2},{"x":1,"y":2},{"x":2,"y":2},{"x":3,"y":2},
        {"x":0,"y":3},{"x":1,"y":3},{"x":2,"y":3},{"x":3,"y":3}
    ] },
    "layers": [{ "name": "base", "bindings": [
        { "type": "key_toggle", "key": "CAPSLOCK" },
        { "type": "key_repeat" },
        { "type": "grave_escape" },
        { "type": "ext_power", "action": "toggle" },
        { "type": "mouse_key", "button": "left" },
        { "type": "mouse_move", "direction": "right" },
        { "type": "mouse_scroll", "direction": "down" },
        { "type": "studio_unlock" },
        { "type": "soft_off" },
        { "type": "output", "action": "bluetooth_next" },
        { "type": "output", "action": "bluetooth_prev" },
        { "type": "output", "action": "toggle" },
        { "type": "macro", "ref": "m_param", "param": "C" },
        { "type": "transparent" },
        { "type": "transparent" },
        { "type": "transparent" }
    ] }],
    "macros": [{
        "id": "m_param", "params": 1,
        "steps": [
            { "type": "press", "key": "LCTRL" },
            { "type": "param" },
            { "type": "pause_for_release" },
            { "type": "release", "key": "LCTRL" }
        ]
    }]
}`

describe('ZMK parity behaviors', () => {
    const dts = String(
        getCompiler('zmk').compile(parseKeymap(EXTRA)).files[0].content,
    )

    it('emits every new behavior token', () => {
        expect(dts).toContain('&kt CAPS')
        expect(dts).toContain('&key_repeat')
        expect(dts).toContain('&gresc')
        expect(dts).toContain('&ext_power EP_TOG')
        expect(dts).toContain('&mkp MB1')
        expect(dts).toContain('&mmv MOVE_RIGHT')
        expect(dts).toContain('&msc SCRL_DOWN')
        expect(dts).toContain('&studio_unlock')
        expect(dts).toContain('&soft_off')
        expect(dts).toContain('&bt BT_NXT')
        expect(dts).toContain('&bt BT_PRV')
        expect(dts).toContain('&out OUT_TOG')
        expect(dts).toContain('#include <dt-bindings/zmk/pointing.h>')
    })

    it('emits a one-param macro and its parametrized call', () => {
        expect(dts).toContain('compatible = "zmk,behavior-macro-one-param"')
        expect(dts).toContain('#binding-cells = <1>')
        expect(dts).toContain('&macro_param_1to1')
        expect(dts).toContain('&macro_pause_for_release')
        expect(dts).toContain('&m_param C')
    })

    it('QMK maps mouse keys and degrades ZMK-only behaviors', () => {
        const c = String(
            getCompiler('qmk').compile(parseKeymap(EXTRA)).files[0].content,
        )
        expect(c).toContain('KC_MS_BTN1')
        expect(c).toContain('KC_MS_RIGHT')
        expect(c).toContain('QK_GESC')
        expect(c).toContain('QK_REP')
    })
})

const COND = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "Cond", "target": "zmk" },
    "keyboard": { "id": "c", "name": "C", "keys": [{"x":0,"y":0}] },
    "layers": [
        { "name": "base", "bindings": ["A"] },
        { "name": "lower", "bindings": ["B"] },
        { "name": "raise", "bindings": ["C"] },
        { "name": "adjust", "bindings": ["D"] }
    ],
    "conditionalLayers": [
        { "ifLayers": ["lower", "raise"], "thenLayer": "adjust" }
    ]
}`

describe('conditional layers', () => {
    it('round-trips through parseKeymap → serialize', () => {
        const cfg = parseKeymap(COND)
        expect(cfg.conditionalLayers).toEqual([
            { ifLayers: ['lower', 'raise'], thenLayer: 'adjust' },
        ])
        const reparsed = parseKeymap(serializeKeymap(cfg))
        expect(reparsed.conditionalLayers).toEqual(cfg.conditionalLayers)
    })

    it('emits a zmk,conditional-layers node with layer indices', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(COND))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('compatible = "zmk,conditional-layers"')
        expect(dts).toContain('if-layers = <1 2>;') // lower=1, raise=2
        expect(dts).toContain('then-layer = <3>;') // adjust=3
    })

    it('QMK warns conditional layers are not generated', () => {
        const { diagnostics } = getCompiler('qmk').compile(parseKeymap(COND))
        expect(
            diagnostics.some((d) => /conditional layers/.test(d.message)),
        ).toBe(true)
    })

    it('rejects a conditional layer referencing an unknown layer', () => {
        const bad = COND.replace('"adjust" }', '"nope" }')
        expect(() => parseKeymap(bad)).toThrow(/unknown layer/)
    })
})

const ENC = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "Enc", "target": "zmk" },
    "keyboard": { "id": "e", "name": "E", "keys": [{"x":0,"y":0}],
        "encoders": [{"x":0,"y":0},{"x":1,"y":0}] },
    "layers": [{ "name": "base", "bindings": ["A"], "encoders": [
        { "cw": "Up", "ccw": "Down" },
        { "cw": { "type": "lighting", "target": "underglow", "action": "brightness_up" },
          "ccw": { "type": "lighting", "target": "underglow", "action": "brightness_down" } }
    ] }]
}`

describe('encoders / sensor-rotate', () => {
    it('emits inc_dec_kp for keypress pairs and a sensor-rotate node otherwise', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(ENC))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        // keypress encoder → inc_dec_kp
        expect(dts).toContain('&inc_dec_kp')
        // non-keypress encoder → generated sensor-rotate behavior node
        expect(dts).toContain('compatible = "zmk,behavior-sensor-rotate"')
        expect(dts).toContain('sr_0_1: sr_0_1 {')
        expect(dts).toContain('&rgb_ug RGB_BRI')
        // layer references both in sensor-bindings
        expect(dts).toMatch(/sensor-bindings = <&inc_dec_kp[^;]*&sr_0_1>;/)
    })

    it('QMK warns encoders are not generated', () => {
        const { diagnostics } = getCompiler('qmk').compile(parseKeymap(ENC))
        expect(diagnostics.some((d) => /encoder/.test(d.message))).toBe(true)
    })
})

const TAILS = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "Tails", "target": "zmk" },
    "keyboard": { "id": "t", "name": "T", "keys": [
        {"x":0,"y":0},{"x":1,"y":0},{"x":2,"y":0},{"x":3,"y":0}
    ] },
    "layers": [{ "name": "base", "bindings": [
        { "type": "output", "action": "bluetooth_disconnect", "profile": 1 },
        { "type": "output", "action": "none" },
        { "type": "lighting", "target": "backlight", "action": "cycle" },
        { "type": "macro", "ref": "swap" }
    ] }],
    "macros": [{
        "id": "swap", "params": 2,
        "steps": [
            { "type": "param", "from": 2, "to": 1 },
            { "type": "tap_time", "ms": 20 },
            { "type": "param", "from": 1, "to": 1 }
        ]
    }]
}`

describe('enum tails + 2-param macros', () => {
    it('emits BT_DISC, OUT_NONE, BL_CYCLE', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(TAILS))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('&bt BT_DISC 1')
        expect(dts).toContain('&out OUT_NONE')
        expect(dts).toContain('&bl BL_CYCLE')
    })

    it('emits a two-param macro with param forwarding and tap_time', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(TAILS))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('compatible = "zmk,behavior-macro-two-param"')
        expect(dts).toContain('#binding-cells = <2>')
        expect(dts).toContain('&macro_param_2to1')
        expect(dts).toContain('&macro_tap_time 20')
    })

    it('round-trips through serialize', () => {
        const cfg = parseKeymap(TAILS)
        const re = parseKeymap(serializeKeymap(cfg))
        expect(re.macros?.[0].params).toBe(2)
        expect(re.macros?.[0].steps).toContainEqual({
            type: 'param',
            from: 2,
            to: 1,
        })
    })
})

const MORPH = `{
    "schemaVersion": 1, "kind": "remappr.keymap",
    "meta": { "name": "Morph", "target": "zmk" },
    "keyboard": { "id": "m", "name": "M", "keys": [{"x":0,"y":0}] },
    "layers": [{ "name": "base", "bindings": [{ "type": "mod_morph", "ref": "dot_colon" }] }],
    "modMorphs": [{
        "id": "dot_colon",
        "mods": ["LEFT_SHIFT", "RIGHT_SHIFT"],
        "keepMods": ["LEFT_GUI"],
        "bindings": [".", ":"]
    }]
}`

describe('mod-morph', () => {
    it('emits a zmk,behavior-mod-morph node with mod flags', () => {
        const dts = String(
            getCompiler('zmk')
                .compile(parseKeymap(MORPH))
                .files.find((f) => f.filename.endsWith('.keymap'))!.content,
        )
        expect(dts).toContain('compatible = "zmk,behavior-mod-morph"')
        expect(dts).toContain('mods = <(MOD_LSFT|MOD_RSFT)>;')
        expect(dts).toContain('keep-mods = <(MOD_LGUI)>;')
        expect(dts).toContain('&dot_colon') // reference in the layer
    })

    it('QMK degrades mod-morph with a warning', () => {
        const { diagnostics } = getCompiler('qmk').compile(parseKeymap(MORPH))
        expect(diagnostics.some((d) => /mod-morph/.test(d.message))).toBe(true)
    })

    it('rejects a reference to an unknown mod-morph', () => {
        const bad = MORPH.replace('"ref": "dot_colon"', '"ref": "nope"')
        expect(() => parseKeymap(bad)).toThrow(/unknown mod-morph/)
    })
})
